[package]
name = "riir"
version = "0.1.0"
authors = ["AleksaC <aleksacukovic1@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"

[[bin]]
name = "day1"
path = "day1/main.rs"

[[bin]]
name = "day2"
path = "day2/main.rs"

[[bin]]
name = "day3"
path = "day3/main.rs"
